/**
 * Single source of truth for Activity Event Types and Sources.
 * No string literals should be used directly in services or API routes.
 */
export const ActivityEvents = {
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  LEAD_CREATED: "LEAD_CREATED",
  CHAT_STARTED: "CHAT_STARTED",
  CHAT_CLOSED: "CHAT_CLOSED",
  CHAT_REOPENED: "CHAT_REOPENED",
  LEAD_ASSIGNED: "LEAD_ASSIGNED",
  CUSTOMER_ASSIGNED: "CUSTOMER_ASSIGNED",
  FOLLOWUP_CREATED: "FOLLOWUP_CREATED",
  FOLLOWUP_COMPLETED: "FOLLOWUP_COMPLETED",
  LEAD_STATUS_CHANGED: "LEAD_STATUS_CHANGED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  ADDRESS_UPDATED: "ADDRESS_UPDATED",
  ADDRESS_CHANGED: "ADDRESS_CHANGED",
  TEMPLATE_SENT: "TEMPLATE_SENT",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSAGE_SENT: "MESSAGE_SENT"
};

export const ActivitySources = {
  WEB: "WEB",
  API: "API",
  WEBHOOK: "WEBHOOK",
  SYSTEM: "SYSTEM",
  BULK_IMPORT: "BULK_IMPORT"
};
