export const NotificationTypes = {
  NEW_MESSAGE: "NEW_MESSAGE",
  NEW_CHAT: "NEW_CHAT",
  ASSOCIATE_LOGIN: "ASSOCIATE_LOGIN",
  ASSOCIATE_LOGOUT: "ASSOCIATE_LOGOUT",
  ADMIN_LOGIN: "ADMIN_LOGIN",
  ADMIN_LOGOUT: "ADMIN_LOGOUT",
  STAFF_ACTIVITY: "STAFF_ACTIVITY",
  LEAD_ASSIGNED: "LEAD_ASSIGNED",
  FOLLOWUP_DUE: "FOLLOWUP_DUE",
  CHAT_REOPENED: "CHAT_REOPENED",
  CUSTOMER_ASSIGNED: "CUSTOMER_ASSIGNED",
  MISSED_CHAT: "MISSED_CHAT",
  SYSTEM_ALERT: "SYSTEM_ALERT"
};
